[build]
  publish = "."
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'nonce-ZXmBngRGKvFl+S0+m0eMxQ=='; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/vendor/*"
  to = "/vendor/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200